translation contribution guide
chaoss/chaoss-slack-bot pull request #97
Opened 2023-10-17 17:15 UTC by ElisaCapololo

This PR is a translation work

## Changes

- translating contribution guide into Portuguese issue  #88 

## Screenshots

![guide](https://github.com/chaoss/chaoss-slack-bot/assets/34274087/92af7223-7fed-409e-806d-0a9d25f101d4)

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [x] updated the docs
- [ ] added a test

Fixes #

2023-10-20 17:48 UTC, aosccode commented
Fixes #88

2023-10-20 17:59 UTC, aosccode requested changes
Thanks a lot for your contribution and your hard work @ElisaCapololo. I just left a couple of comm

2023-10-20 17:59 UTC, aosccode commented on Translations/Portuguese/Basic Information.md
>  This is the link  to the slack bot wiki basic information page to be translated.
I don't think we need this line here :)

2023-10-20 17:59 UTC, aosccode commented on Translations/Portuguese/Basic Information.md
> +> ### Informação básica
Should it be `Informações básicas`?

2023-10-20 17:59 UTC, aosccode commented on Translations/Portuguese/Basic Information.md
> +> #### Funções do bot
It should be `Funcionalidades do bot` in IMHO :)

2023-10-20 17:59 UTC, aosccode commented on Translations/Portuguese/Getting Started With Bolt For Javascript.md
You are fixing more than one issue, you should mention that.

I see this PR fixes #90, #85, #83, and #88 

Either you use this PR to fix all the issues, or open a new PR for each issue. 
I am not sure fixing all four issues in one PR will be counted as 4 PRs. Please choose wisely :)

2023-10-20 17:59 UTC, aosccode commented on Translations/Portuguese/Contribution Guide.md
> +Se você estiver enfrentando problemas com o CHAOSS Slack Bot ou tiver alguma dúvida que gostaria de ajuda para responder, sinta-se à vontade para abrir um [issue](https://github.com/chaoss/chaoss-sla
It should be nice if we have one line per sentence. 
@Busayo-ojo do you have any thoughts?

2023-10-20 17:59 UTC, aosccode commented on Translations/Portuguese/Contribution Guide.md
> +## Signing-off em Commits
Adicione assinatura nos commits :)

2023-10-20 18:02 UTC, aosccode commented
I have seen that #85 has being fixed by #92 and it was submitted earlier than this PR :)

2023-10-22 08:36 UTC, antonio-pedro99 commented
Hi @ElisaCapololo, can you remove the translation of the Contributing Guide from this PR? It is being fixed by #85 already
BTW, are you addressing my comments?

2023-10-22 08:49 UTC, antonio-pedro99 commented on Translations/Portuguese/Getting Started With Bolt For Javascript.md
As this PR is solving what #92 is already fixing, and other changes are unrelated to the issue, I think we should close this PR.
CC: @Busayo-ojo

2023-10-23 21:12 UTC, Busayo-ojo commented
Thanks for working on this @ElisaCapololo!

2023-10-23 21:12 UTC, merged